# Generated by Django 4.1.3 on 2023-08-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='java',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=30)),
                ('phone_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
