# Generated by Django 4.1.3 on 2023-08-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_python_joiners'),
    ]

    operations = [
        migrations.CreateModel(
            name='java_joiners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='testing_joiners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=15)),
            ],
        ),
    ]
