# Generated by Django 4.1.3 on 2023-08-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_java_joiners_testing_joiners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='python_joiners',
            old_name='Name',
            new_name='name',
        ),
    ]
