# Generated by Django 4.1.3 on 2023-08-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_rename_name_python_joiners_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='java_joiners',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='testing_joiners',
            old_name='Name',
            new_name='name',
        ),
    ]
