# Generated by Django 4.1.3 on 2023-08-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_rename_name_java_joiners_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='python_joiners',
            old_name='name',
            new_name='names',
        ),
    ]
